# config/dpo_config.yaml
model:
  name: "unsloth/Qwen2.5-1.5B-Instruct"
  max_seq_length: 2048
  training_type: "sft"  # "sft", "lora", "qlora" 중 선택

peft:  # LoRA/QLoRA에만 적용
  r: 16
  lora_alpha: 16
  use_qlora: false

data:
  num_proc: 2
  train_path: "./data/train/train.csv"
  val_path: "./data/test/gemini_test_result.csv"

training:
  batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 1000
  epochs: 3
  learning_rate: 3e-5
  eval_steps: 1000
  logging_steps: 500
  optimizer: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 3407
  save_steps: 1000
  save_total_limit: 3

dpo:
  beta: 0.1  # DPO 손실의 하이퍼파라미터
  max_prompt_length: 512  # 프롬프트 최대 길이